import TransactionList from "./components/transactionList";
import { Suspense } from "react";
import TransactionListFallback from "./components/transactionListSkeleton";
import DashboardTrend from "./components/dashboardTrend";
import TrendFallback from "./components/trendSkeleton";
import Link from "next/link";
import {PlusCircle} from 'lucide-react'
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Caio",
};

export default function Dashboard() {
    return (        
            <div className="flex flex-col">

                <h1>
                    Dashboard
                </h1>
                <div>
                    <Suspense fallback={<TrendFallback/>}>
                        <DashboardTrend/>
                    </Suspense>
                    
                </div>
                <hr/>

                <div className="flex justify-between items-center mb-4">
                    <h2>
                        Summary
                    </h2>

                    <Link href="/dashboard/transaction/add" className="flex rounded-md p-2 items-center bg-green-500">
                        <PlusCircle className="w-4 h-4 mr-1" />
                        Add 
                    </Link> 

                </div>
                    

                <div>
                    <Suspense fallback={<TransactionListFallback/>}>
                        <TransactionList/>
                    </Suspense>
    
                </div>
    
            </div>
    )
}