import TransactionList from "./components/transactionList";
import { Suspense } from "react";
import TransactionListFallback from "./components/transactionListSkeleton";
import DashboardTrend from "./components/dashboardTrend";
import TrendFallback from "./components/trendSkeleton";
import Link from "next/link";
import {PlusCircle} from 'lucide-react'
import { Metadata } from "next";
import { ErrorBoundary } from "react-error-boundary";
import Range from "./components/range";
import { getStartDate } from "@/utils/getDateRange";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Caio",
};

type DashboardProps = {
   range?: string
}

export default async function Page({ searchParams } : { searchParams : DashboardProps}){

    const dateRange = getStartDate((await searchParams).range)

    return (        
            <div className="flex flex-col">

                <h1>
                    Dashboard
                </h1>
                <div>
                    <ErrorBoundary fallback={<p className="text-red-400">Cannot fetch trend data</p>}>
                        <Suspense fallback={<TrendFallback/>}>
                            <DashboardTrend startDate={dateRange} />
                        </Suspense>
                    </ErrorBoundary>
                    
                </div>
                <hr/>

                <div className="flex justify-between items-center mb-4">
                    <h2>
                        Summary
                    </h2>

                    <aside>
                        <Range/>
                    </aside>

                </div>

                <div className="flex justify-end">    
                    <Link href="/dashboard/transaction/add" className="flex rounded-md p-2 items-center bg-green-400 dark:bg-green-500">
                        <PlusCircle className="w-4 h-4 mr-1" />
                        Add 
                    </Link> 
                </div>

                <div>
                    <ErrorBoundary fallback={<h2>Something went wrong</h2>}>
                        <Suspense fallback={<TransactionListFallback/>}>
                            <TransactionList startDate={dateRange}/>
                        </Suspense>
                    </ErrorBoundary>
    
                </div>
    
            </div>
    )
}
